interface Vod {
    vodId: number,
    typeId: number,
    typeId1: number,
    groupId: number,
    vodName: string,
    vodEn: string,
    vodStatus: number,
    vodLetter: string,
    vodClass: string,
    vodPic: string,
    vodTotal: number,
    vodSerial: number,
    vodIsend: number,
    vodLock: number,
    vodLevel: number,
    vodCopyright: number,
    vodPoints: number,
    vodPointsPlay: number,
    vodPointsDown: number,
    vodHits: number,
    vodHitsDay: number,
    vodHitsWeek: number,
    vodHitsMonth: number,
    vodUp: number,
    vodDown: number,
    vodScore: number,
    vodScoreAll: number,
    vodScoreNum: number,
    vodTime: number,
    vodTimeAdd: number,
    vodTimeHits: number,
    vodTimeMake: number,
    vodTrysee: number,
    vodDoubanId: number,
    vodDoubanScore: number,
    vodPlayFrom: string,
    vodPlayServer: string,
    vodPlayUrl: string,
    vodPlot: number,
    status: number,
    permission: number
}

export default Vod