import React, { ReactNode } from 'react'
import Head from 'next/head'
import HeaderBar from './HeaderBar'
import FooterBar from './FooterBar'

type LayoutProps = {
    children: ReactNode
}

function Layout({children}: LayoutProps) {
    return (
        <div className="dark">
            <div className="bg-gray-50 dark:bg-gray-800">
                <Head>
                    <title>巨硬AV</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <HeaderBar></HeaderBar>
                <div className="pt-12 sm:pt-16">{children}</div>
                <FooterBar></FooterBar>
            </div>
        </div>
    )
}

export default Layout