import Head from 'next/head'
import LazyLoad from 'react-lazyload'
import { GetServerSideProps } from 'next'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faChevronRight } from '@fortawesome/free-solid-svg-icons'
import HeaderBar from '../components/HeaderBar'
import FooterBar from '../components/FooterBar'
import VodType from '../types/VodType'
import Vod from '../types/Vod'


const getVodTypes = async () => {
  const res = await fetch('https://jyavs.com/api/type/findAll')
  const data = await res.json()
  if (!data || data.code != 200) {
    return null
  }
  return data.data
}

const getVodsNew = async () => {
  const res = await fetch('https://jyavs.com/api/vod/homeNew?num=12')
  const data = await res.json()
  if (!data || data.code != 200) {
    return null
  }
  return data.data
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const vodTypes = await getVodTypes()
  const vodsNewList = await getVodsNew()
  return {
    props: {
      vodTypes,
      vodsNewList
    }
  }
}

type HomeProps = {
  vodTypes: Array<VodType>,
  vodsNewList: Array<VodType>
}

export default function Home({ vodTypes, vodsNewList }: HomeProps) {
  return (
    <div className="bg-gray-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderBar vodTypes={vodTypes}></HeaderBar>

      <main className="pt-16">
        <div className="h-36 sm:h-48 md:h-60 lg:h-72 xl:h-80 2xl:h-96 bg-gray-500 text-9xl text-gray-300 flex items-center justify-center">
          BANNER
        </div>
        <div className="container pt-6">
          {
            vodsNewList.map((vodsNew: VodType) => (
              <div className="mb-6" key={vodsNew.typeId}>
                <div className="py-4 px-4">
                  <h2 className="text-lg text-gray-700 inline-block">最新{vodsNew.typeName}</h2>
                  <a className="text-sm text-gray-400 inline-block ml-2" href="#">更多</a>
                  <FontAwesomeIcon className="w-2 text-gray-400 inline-block " icon={faChevronRight}/>
                </div>
                <div className="px-4 grid gap-4 grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
                  {
                    vodsNew && vodsNew.vods && vodsNew.vods.map((vod: Vod) => (
                      <a 
                        className="bg-white shadow-md overflow-hidden rounded-lg" 
                        href="#"
                        title={vod.vodName}
                        key={vod.vodId}>
                        <div className="aspectration" data-ratio="4:3">
                          <div className="con">
                            <LazyLoad height="100%">
                              <img className="object-cover h-full" src={vod.vodPic} alt="" />
                            </LazyLoad>
                          </div>
                        </div>
                        <div className="p-3 leading-relaxed">
                          <h3 className="text-gray-700 truncate">{vod.vodName}</h3>
                          <p className="text-gray-400 text-sm">{vod.vodClass}</p>
                        </div>
                      </a>
                    ))
                  }
                </div>
              </div>
            ))
          }
        </div>
      </main>

      <FooterBar></FooterBar>
    </div>
  )
}
